server:
  port: 8082

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**

        - id: hello-microservice
          uri: lb://hello-microservice
          predicates:
            - Path=/api/hello/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
